// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjbUjEf0mkJwVk0DHLkrbG_ab_zIW7fw',
    appId: '1:740379897294:web:98499458890ea9083b0f9f',
    messagingSenderId: '740379897294',
    projectId: 'flutter-chat-application-198b7',
    authDomain: 'flutter-chat-application-198b7.firebaseapp.com',
    storageBucket: 'flutter-chat-application-198b7.appspot.com',
    measurementId: 'G-YJ88E53ZN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCviqda-6RMXE8P17fwphIaU6OgHO2NT74',
    appId: '1:740379897294:android:6ec719899c3b333c3b0f9f',
    messagingSenderId: '740379897294',
    projectId: 'flutter-chat-application-198b7',
    storageBucket: 'flutter-chat-application-198b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHruu_o0dVYYCSFoSinVZjZXlhLV5-Yaw',
    appId: '1:740379897294:ios:056cfa89901765273b0f9f',
    messagingSenderId: '740379897294',
    projectId: 'flutter-chat-application-198b7',
    storageBucket: 'flutter-chat-application-198b7.appspot.com',
    iosBundleId: 'com.example.flutterChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHruu_o0dVYYCSFoSinVZjZXlhLV5-Yaw',
    appId: '1:740379897294:ios:aa866c7fb4ef0d5c3b0f9f',
    messagingSenderId: '740379897294',
    projectId: 'flutter-chat-application-198b7',
    storageBucket: 'flutter-chat-application-198b7.appspot.com',
    iosBundleId: 'com.example.flutterChatApplication.RunnerTests',
  );
}
