name: flutter_chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #chat using socket
  socket_io_client: ^2.0.0
  emoji_picker_flutter: ^2.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: OpenSans
    fonts:
      - asset: fonts/OpenSans-Bold.ttf
      - asset: fonts/OpenSans-Regular.ttf
      - asset: fonts/OpenSans-SemiBold.ttf
      - asset: fonts/OpenSans-Italic.ttf
        style: italic
