name: flutter_chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  appwrite: ^11.0.1
  intl_phone_number_input: ^0.7.4
  country_picker: ^2.0.24
  emoji_picker_flutter: ^2.0.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  lottie: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

fonts:
  - family: OpenSans
    fonts:
      - asset: fonts/OpenSans-Bold.ttf
      - asset: fonts/OpenSans-Regular.ttf
      - asset: fonts/OpenSans-SemiBold.ttf
      - asset: fonts/OpenSans-Italic.ttf
        style: italic
